version: '3.8'

services:
  # Message Broker
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"

  # Databases
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Auth Service
  auth-service:
    build: ./auth-service
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
      - redis
      - kafka

  # User Service
  user-service:
    build: ./user-service
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - AUTH_SERVICE_URL=http://auth-service:8000
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
      - redis
      - kafka
      - auth-service

  # Service Management
  service-service:
    build: ./service-service
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - AUTH_SERVICE_URL=http://auth-service:8000
    ports:
      - "8003:8000"
    depends_on:
      - mongodb
      - redis
      - kafka
      - auth-service

  # Realtime Service  
  realtime-service:
    build: ./realtime-service
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - AUTH_SERVICE_URL=http://auth-service:8000
    ports:
      - "8004:8000"
    depends_on:
      - mongodb
      - redis
      - kafka
      - auth-service

  # Notification Service
  notification-service:
    build: ./notification-service
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - EXPO_ACCESS_TOKEN=your-expo-access-token
    ports:
      - "8005:8000"
    depends_on:
      - mongodb
      - redis
      - kafka

  # Payment Service
  payment-service:
    build: ./payment-service
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
      - STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret
    ports:
      - "8006:8000"
    depends_on:
      - mongodb
      - redis
      - kafka

  # Chat Service
  chat-service:
    build: ./chat-service
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - AUTH_SERVICE_URL=http://auth-service:8000
    ports:
      - "8007:8000"
    depends_on:
      - mongodb
      - redis
      - kafka
      - auth-service

  # Analytics Service
  analytics-service:
    build: ./analytics-service
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "8008:8000"
    depends_on:
      - mongodb
      - redis
      - kafka

  # API Gateway
  api-gateway:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - auth-service
      - user-service
      - service-service
      - realtime-service
      - notification-service
      - payment-service
      - chat-service
      - analytics-service

volumes:
  mongodb_data:
  redis_data: